import {
  LayoutDashboard,
  ShoppingBag,
  Download,
  Heart,
  Users,
  Bell,
  User,
  FolderKanban,
  UploadCloud,
  FileEdit,
  CheckCircle2,
  CheckCircle,
  BarChart3,
  Layers,
  UserSquare2,
  Settings,
  Star,
  Wallet,
  Ticket,
} from 'lucide-react';

export const accountLinks = [
  { to: '/account', label: 'Dashboard', icon: LayoutDashboard, end: true },
  { to: '/account/profile', label: 'Profile', icon: User },
  { to: '/explore', label: 'My Purchases', icon: ShoppingBag },
  { to: '/explore', label: 'Downloads', icon: Download },
  { to: '/explore', label: 'Wishlist', icon: Heart },
  { to: '/explore', label: 'Following', icon: Users },
  { to: '/explore', label: 'Notifications', icon: Bell },
];

export const creatorLinks = [
  { to: '/creator', label: 'Studio', icon: LayoutDashboard, end: true },
  { to: '/creator/profile', label: 'Creator Profile', icon: UserSquare2 },
  { to: '/explore', label: 'Assets', icon: Layers },
  { to: '/explore', label: 'Upload Asset', icon: UploadCloud },
  { to: '/explore', label: 'Drafts', icon: FileEdit, count: 6 },
  { to: '/explore', label: 'Pending Review', icon: CheckCircle, count: 3 },
  { to: '/explore', label: 'Published', icon: CheckCircle2, count: 28 },
  { to: '/explore', label: 'Analytics', icon: BarChart3 },
  { to: '/explore', label: 'Collections', icon: FolderKanban },
  { to: '/explore', label: 'Followers', icon: Users, count: '1.2K' },
  { to: '/explore', label: 'Reviews', icon: Star, count: 47 },
  { to: '/explore', label: 'Payouts', icon: Wallet },
  { to: '/explore', label: 'Coupons', icon: Ticket },
  { to: '/explore', label: 'Store Settings', icon: Settings },
];
