services:
  # mongodb:
  #   image: mongo:7
  #   container_name: mongodb
  #   restart: unless-stopped

  #   ports:
  #     - '27017:27017'

  #   volumes:
  #     - mongo-data:/data/db
  #     - mongo-configdb:/data/configdb

  auth-service:
    build:
      context: .
      dockerfile: ./server/services/auth-service/DockerFile

    container_name: auth-service

    ports:
      - '5001:5001'
    volumes:
      - .:/app
      - root-node-modules:/app/node_modules
      - auth-node-modules:/app/server/services/auth-service/node_modules

    env_file:
      - ./server/services/auth-service/config.env

    # depends_on:
    #   - mongodb
  user-service:
    build:
      context: .
      dockerfile: ./server/services/user-service/DockerFile

    container_name: user-service

    ports:
      - '5002:5002'
    volumes:
      - .:/app
      - root-node-modules:/app/node_modules
      - user-node-modules:/app/server/services/user-service/node_modules

    env_file:
      - ./server/services/user-service/config.env

    # depends_on:
    #   - mongodb

  asset-service:
    build:
      context: .
      dockerfile: ./server/services/asset-service/DockerFile

    container_name: asset-service

    ports:
      - '5003:5003'
    volumes:
      - .:/app
      - root-node-modules:/app/node_modules
      - asset-node-modules:/app/server/services/asset-service/node_modules

    env_file:
      - ./server/services/asset-service/config.env

    # depends_on:
    #   - mongodb

volumes:
  # mongo-data:
  # mongo-configdb:
  root-node-modules:
  auth-node-modules:
  user-node-modules:
  asset-node-modules:
