version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped

    ports:
      - '27017:27017'

    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

  auth-service:
    build:
      context: .
      dockerfile: ./server/services/authService/DockerFile

    container_name: auth_service

    ports:
      - '5001:5001'
    volumes:
      - .:/app
      - root-node-modules:/app/node_modules
      - auth-node-modules:/app/server/services/authService/node_modules

    depends_on:
      - mongodb
  user-service:
    build:
      context: .
      dockerfile: ./server/services/userService/DockerFile

    container_name: user_service

    ports:
      - '5002:5002'
    volumes:
      - .:/app
      - root-node-modules:/app/node_modules
      - user-node-modules:/app/server/services/userService/node_modules

    depends_on:
      - mongodb

  asset-service:
    build:
      context: .
      dockerfile: ./server/services/assetService/DockerFile

    container_name: asset_service

    ports:
      - '5003:5003'
    volumes:
      - .:/app
      - root-node-modules:/app/node_modules
      - asset-node-modules:/app/server/services/assetService/node_modules

    depends_on:
      - mongodb

volumes:
  mongo-data:
  mongo-configdb:
  root-node-modules:
  auth-node-modules:
  user-node-modules:
  asset-node-modules:
