version: '3.9'
services:
  # mongodb:
  #   image: mongo:7
  #   container_name: mongodb
  #   restart: unless-stopped

  #   ports:
  #     - '27017:27017'

  #   volumes:
  #     - mongo-data:/data/db
  #     - mongo-configdb:/data/configdb
  gateway:
    build:
      context: .
      dockerfile: ./server/gateway/Dockerfile

    container_name: render_cube_gateway

    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - root-node-modules:/app/node_modules
      - gateway-node-modules:/app/server/gateway/node_modules

    env_file:
      - ./server/gateway/config.env

    depends_on:
      - auth-service
      - user-service
      - asset-service
    networks:
      - render_cube_network

  auth-service:
    build:
      context: .
      dockerfile: ./server/services/auth-service/Dockerfile

    container_name: render_cube_auth

    ports:
      - '5001:5001'
    volumes:
      - .:/app
      - root-node-modules:/app/node_modules
      - auth-node-modules:/app/server/services/auth-service/node_modules

    env_file:
      - ./server/services/auth-service/config.env

    networks:
      - render_cube_network

    # depends_on:
    #   - mongodb
  user-service:
    build:
      context: .
      dockerfile: ./server/services/user-service/Dockerfile

    container_name: render_cube_user

    ports:
      - '5002:5002'
    volumes:
      - .:/app
      - root-node-modules:/app/node_modules
      - user-node-modules:/app/server/services/user-service/node_modules

    env_file:
      - ./server/services/user-service/config.env

    networks:
      - render_cube_network

    # depends_on:
    #   - mongodb

  asset-service:
    build:
      context: .
      dockerfile: ./server/services/asset-service/Dockerfile

    container_name: render_cube_asset

    ports:
      - '5003:5003'
    volumes:
      - .:/app
      - root-node-modules:/app/node_modules
      - asset-node-modules:/app/server/services/asset-service/node_modules

    env_file:
      - ./server/services/asset-service/config.env

    networks:
      - render_cube_network

    # depends_on:
    #   - mongodb

volumes:
  # mongo-data:
  # mongo-configdb:
  root-node-modules:
  gateway-node-modules:
  auth-node-modules:
  user-node-modules:
  asset-node-modules:

networks:
  render_cube_network:
    driver: bridge
